name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ldid
        run: |
          curl -sL -o /tmp/ldid https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_linux_x86_64
          sudo install -m755 /tmp/ldid /usr/local/bin/ldid
      - name: Build with Theos
        uses: theos/theos-github-action@master
        with:
          scheme: rootless
      - uses: actions/upload-artifact@v4
        with:
          name: deb
          path: packages/*.deb
